### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by eric-nie** [Symph0nia/CyberEdge#15]
![image](https://github.com/user-attachments/assets/a3183656-a171-4a99-8da1-42ae1a5620dd)
挂代理也一样

**Comment by ZacharyZcR** [comment]
您好，本报错原因为您使用的Docker源被中国大陆所屏蔽导致，可以参考以下解决方案，希望我的回复能帮到您，如有任何疑问请继续联系。

Hello, the reason for this error is that the Docker source you are using is blocked in mainland China. You can refer to the following solutions. I hope my response can help you. If you have any questions, please feel free to contact me again.

https://www.cnblogs.com/Undefined443/p/17975800
https://neucrack.com/p/286

**Comment by eric-nie** [comment]
好了，感谢
