### ISSUE TITLE
部署有问题，缺少  requirements.txt 文件

### ISSUE THREAD

**Issue by J-Snowwite** [Symph0nia/CyberEdge#18]
[root@centos7 CyberEdge]# docker compose up -d
WARN[0000] The "POSTGRES_USER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "POSTGRES_DB" variable is not set. Defaulting to a blank string. 
WARN[0000] /root/CyberEdge/docker-compose.yaml: `version` is obsolete 
[+] Building 6.1s (10/13)                                                                                                              docker:default
 => [django-backend internal] load build definition from Dockerfile.backend                                                                      0.0s
 => => transferring dockerfile: 1.31kB                                                                                                           0.0s
 => [django-backend internal] load metadata for docker.io/library/python:3.10-slim                                                               4.4s
 => [django-backend internal] load .dockerignore                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                  0.0s
 => [django-backend 1/9] FROM docker.io/library/python:3.10-slim@sha256:af6f1b19eae3400ea3a569ba92d4819a527be4662971d51bb798c923bba30a81         0.0s
 => [django-backend internal] load build context                                                                                                 0.0s
 => => transferring context: 4.67kB                                                                                                              0.0s
 => CACHED [django-backend 2/9] RUN apt-get update && apt-get install -y     aria2     wget     git     tar     nmap                             0.0s
 => CACHED [django-backend 3/9] RUN ln -s /usr/local/bin/python3 /usr/bin/python3                                                                0.0s
 => CACHED [django-backend 4/9] WORKDIR /app                                                                                                     0.0s
 => CACHED [django-backend 5/9] COPY . /app                                                                                                      0.0s
 => ERROR [django-backend 6/9] RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt                    1.6s
------                                                                                                                                                
 > [django-backend 6/9] RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt:                               
1.152 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'                                                
1.508 
1.508 [notice] A new release of pip is available: 23.0.1 -> 24.3.1
1.508 [notice] To update, run: pip install --upgrade pip
------
failed to solve: process "/bin/sh -c pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt" did not complete successfully: exit code: 1

**Comment by b2522** [comment]
同样遇到这个问题，自建了一个requirements.txt文件，里面没写内容，可以继续，后面会遇到这个问题。


 => ERROR [nginx-frontend 2/4] COPY ./dist /usr/share/nginx/html                                                                                   0.0s
------
 > [nginx-frontend 2/4] COPY ./dist /usr/share/nginx/html:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref c8de6233-a710-41d5-87e0-06c53012b564::w3dbiow8221clfaxiw8yokvgl: "/dist": not found

**Comment by ZacharyZcR** [comment]
您好，目前最新版本的CyberEdge已经由Golang驱动，请重新尝试新版本部署，感谢支持。
