### ISSUE TITLE
Nmap版本不对相关命令不存在

### ISSUE THREAD

**Issue by 9mlcy7** [Symph0nia/CyberEdge#24]
ERROR: 2024/12/18 03:36:55.505143 handler.go:46 处理任务失败 [nmap]: 执行 Nmap 命令失败: exit status 255, 输出: nmap: unrecognized option '--unique'
See the output of nmap -h for a summary of options.

**Comment by ZacharyZcR** [comment]
您好，请检查一下前端页面中，系统配置-工具配置中，Nmap指示灯是否亮起，如无，请检查是使用Docker安装还是二进制文件安装，如果使用二进制文件安装，请自行安装Nmap，并添加进入系统目录。

感谢您的反馈

**Comment by 9mlcy7** [comment]
后端容器内是安装了nmap的，估计是安装脚本每次都安装的最新版，导致有些命令已经不支持了，建议在脚本固定相关工具的版本
![image](https://github.com/user-attachments/assets/b283f925-9d7c-48f1-9443-b00cb8b032f6)
![image](https://github.com/user-attachments/assets/12a847e1-79bc-4399-9fdb-576ed2e32135)

**Comment by ZacharyZcR** [comment]
收到，我这边马上复现一下问题，请稍等

**Comment by 9mlcy7** [comment]
> 收到，我这边马上复现一下问题，请稍等

FROM --platform=linux/amd64 ubuntu:22.04

**Comment by ZacharyZcR** [comment]
修复完成，劳烦再次测试确认情况。

**Comment by 9mlcy7** [comment]
> 修复完成，劳烦再次测试确认情况。

感谢你及时回复，已经没有问题了
